CREATE TABLE IF NOT EXISTS hotels (
    hotel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (200) NOT NULL,
    description VARCHAR (500) NOT NULL,
    country VARCHAR (50) NOT NULL,
    state VARCHAR (50) NOT NULL,
    city VARCHAR (50) NOT NULL,
    zip_code VARCHAR (10) NOT NULL,
    address VARCHAR (300) NOT NULL,
    rating NUMERIC (2, 1) NOT NULL
    );

CREATE TABLE IF NOT EXISTS amenities (
    amenity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (200) NOT NULL,
    description VARCHAR (500)
    );

CREATE TABLE IF NOT EXISTS hotel_amenities (
    hotel_id BIGINT,
    amenity_id BIGINT,
    PRIMARY KEY (hotel_id, amenity_id),
    FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id),
    FOREIGN KEY (amenity_id) REFERENCES amenities (amenity_id)
    );