CREATE TABLE IF NOT EXISTS hotels (
    hotel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(50) NOT NULL,
    --country_code VARCHAR(3) NOT NULL,
    state VARCHAR(50) NOT NULL,
    city VARCHAR(50) NOT NULL,
    zip_code VARCHAR(10) NOT NULL,
    address1 VARCHAR(100) NOT NULL,
    address2 VARCHAR(100),
    address3 VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

CREATE TABLE IF NOT EXISTS amenities (
    amenity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

CREATE TABLE IF NOT EXISTS hotel_amenities (
    hotel_id BIGINT,
    amenity_id BIGINT,
    PRIMARY KEY (hotel_id, amenity_id),
    FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id),
    FOREIGN KEY (amenity_id) REFERENCES amenities (amenity_id)
    );

CREATE TABLE IF NOT EXISTS hotel_ratings (
    rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id BIGINT,
    score INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (hotel_id) REFERENCES hotels (hotel_id)
    );
